# Generated by Django 4.0.4 on 2022-04-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_person_admin_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='invited_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='manager_app.person'),
        ),
    ]
