# Generated by Django 4.0.4 on 2022-04-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_task_invited_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='invited_person',
            new_name='guest',
        ),
    ]
